spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db
    username: root
    password: chenxiaofeng
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3